// Converts art-source/poc-xi/moon-library.ldtk into dist/poc-xi/levels.js (room rows + entities for world.js).
// Collision: IntGrid 1 = wall '#', 2 = one-way platform '='. Standing entities (Skeleton, Item, Shrine) sit in the open
// cell above the floor; the exporter converts to the game's surface-row convention (ty = floor row).
import {readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export function exportLevels(project) {
  const levels = {};
  for (const lv of project.levels) {
    const layers = Object.fromEntries(lv.layerInstances.map(l => [l.__identifier, l]));
    const {__cWid: w, __cHei: h, intGridCsv} = layers.Collision;
    const rows = Array.from({length: h}, (_, y) => intGridCsv.slice(y * w, (y + 1) * w).map(v => ({1: '#', 2: '='})[v] || '.').join(''));
    const f = e => Object.fromEntries(e.fieldInstances.map(i => [i.__identifier, i.__value]));
    const entities = [], props = [];
    for (const e of layers.Entities.entityInstances) {
      const [cx, cy] = e.__grid, v = f(e), k = e.__identifier;
      if (k === 'Skeleton') entities.push({type: 'skeleton', tx: cx, ty: cy + 1, a: v.a, b: v.b, range: v.range});
      else if (k === 'Bat') entities.push({type: 'bat', tx: cx, ty: cy, a: v.a, b: v.b, range: v.range});
      else if (k === 'Shrine') entities.push({type: 'shrine', id: v.shrineId, tx: cx, ty: cy + 1, orbs: String(v.orbs).split(',').filter(Boolean).map(Number)});
      else if (k === 'Block') entities.push({type: 'block', id: v.blockId, tx: cx, ty: cy, tw: e.width / 32, th: e.height / 32, product: v.product});
      else if (k === 'Item') entities.push({type: 'item', id: v.itemId, kind: v.kind, tx: cx, ty: cy + 1, ...(v.via ? {via: v.via} : {})});
      else if (k === 'Prop') props.push({frame: v.frame, x: e.px[0], y: e.px[1]});
      else throw new Error(`Unknown LDtk entity ${k}`);
    }
    levels[lv.identifier] = {rows, entities, props};
  }
  return levels;
}
export function render(levels) {
  return `// Generated by scripts/ldtk-export.mjs from art-source/poc-xi/moon-library.ldtk. Edit the .ldtk in LDtk, not this file.\nexport const LEVELS = ${JSON.stringify(levels, null, 1)};\n`;
}
if (process.argv[1] && process.argv[1].endsWith('ldtk-export.mjs')) {
  const project = JSON.parse(readFileSync(join(root, 'art-source/poc-xi/moon-library.ldtk'), 'utf8'));
  writeFileSync(join(root, 'dist/poc-xi/levels.js'), render(exportLevels(project)));
  console.log('wrote dist/poc-xi/levels.js');
}
