import { requireApiUser } from "@/lib/auth";
import { assertRoomAccess } from "@/lib/retrieval";
import { generateLocalFlashcards, retrievalServiceConfigured } from "@/lib/retrieval-client";

export const runtime = "nodejs";
export const maxDuration = 30;

/**
 * Zero-LLM flashcards: cloze and true/false cards generated by the local
 * Python retrieval service (services/retrieval) via spaCy POS/NER rules,
 * not a language model. Separate from GET/POST /api/flashcards, which reads
 * and reviews the learner's real spaced-repetition deck; this is a
 * generation preview that works even with no OPENAI_API_KEY configured,
 * provided a document has already been indexed into that room (ingestion
 * mirrors pages into it automatically — see lib/ingest.ts).
 */
export async function POST(request: Request) {
  const { supabase, user, unauthorized } = await requireApiUser();
  if (!user) return unauthorized;

  if (!retrievalServiceConfigured()) {
    return Response.json(
      { error: "The local retrieval service isn't configured (RETRIEVAL_SERVICE_URL is unset)." },
      { status: 503 }
    );
  }

  const body = (await request.json().catch(() => null)) as {
    roomId?: string;
    query?: string;
    clozeCount?: number;
    trueFalseCount?: number;
  } | null;
  const roomId = body?.roomId?.trim();
  if (!roomId) return Response.json({ error: "roomId is required" }, { status: 400 });

  const room = await assertRoomAccess(supabase, roomId);
  if (!room) return Response.json({ error: "Study Room not found." }, { status: 404 });

  try {
    const result = await generateLocalFlashcards({
      roomId,
      query: body?.query,
      clozeCount: body?.clozeCount,
      trueFalseCount: body?.trueFalseCount
    });
    if (!result) {
      return Response.json({ error: "The local retrieval service returned nothing." }, { status: 502 });
    }
    return Response.json(result);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Local flashcard generation failed.";
    return Response.json({ error: message }, { status: 502 });
  }
}
